### ISSUE TITLE
Siri on iPad not working

### ISSUE THREAD

**Issue by Quorum75** [Cybo1927/Hosts#75]
## Issue Description
Siri does not work on my iPad but it works on the iPhone. 

## Issue Details
When I call’Siri on the iPad it says it has a connection problem. 
If I uncheck the DNS Host in AdGuard then I can get Siri. 

- **List:**
Host

- **Browser:**
Safari but not applicable.

**Comment by Cybo1927** [comment]
I'm currently not home and won't be for another couple of days, can you try to find the problematic things being blocked? I also don't know if I'd be able to find the domain myself because Siri worked perfectly fine on my iPad Mini 2 last I checked

I'll work on this as soon as I get home, thanks for bringing this to my attention!
